<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <UseWindowsForms>true</UseWindowsForms>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Portal.CredentialProvider</RootNamespace>
        <AssemblyName>Portal.CredentialProvider</AssemblyName>
        <EnableComHosting>true</EnableComHosting>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>true</PublishReadyToRun>
        <PublishReadyToRunComposite>false</PublishReadyToRunComposite>
        <PublishTrimmed>false</PublishTrimmed>
        <TieredCompilation>true</TieredCompilation>
        <TieredCompilationQuickJit>true</TieredCompilationQuickJit>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Assets\logo.bmp" />
        <None Remove="Assets\portal-icon.png" />
        <None Remove="Assets\tile-icon.bmp" />
        <None Remove="Assets\tile-icon.png" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Assets\portal-icon.png" />
        <EmbeddedResource Include="Assets\tile-icon.png" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Lithnet.CredentialProvider" Version="1.1.27" />

        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <ProjectReference Include="..\Portal.Common\Portal.Common.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <Authors>xXKoksMenXx</Authors>
        <Company>xXTeam</Company>
        <Product>Portal Credential Provider (Windows)</Product>
        <Copyright>Copyright © 2026</Copyright>
    </PropertyGroup>

    <Target Name="SignOutput" AfterTargets="Build" Condition="'$(Configuration)' == 'Release' And '$(SkipSigning)' != 'true'">
        <Exec
            Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;110025BF33D9D8EEE632AD6C4F43618A24069B22&quot; /tr http://timestamp.acs.microsoft.com /td sha256 /fd sha256 &quot;$(TargetPath)&quot;" />
        <Exec
            Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;110025BF33D9D8EEE632AD6C4F43618A24069B22&quot; /tr http://timestamp.acs.microsoft.com /td sha256 /fd sha256 &quot;$(TargetDir)$(TargetName).comhost.dll&quot;"
            Condition="Exists('$(TargetDir)$(TargetName).comhost.dll')" />
    </Target>

</Project>
