<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>Assets\portal-icon.ico</ApplicationIcon>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Portal.Host</RootNamespace>
        <AssemblyName>Portal.Host</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <Resource Include="Assets\portal-icon.png" />
    </ItemGroup>

    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
        <PackageReference Include="QRCoder" Version="1.6.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="System.Management" Version="9.0.8" />
        <ProjectReference Include="..\Portal.Common\Portal.Common.csproj" />
        <ProjectReference Include="..\Portal.CredentialProvider\Portal.CredentialProvider.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
        <ProjectReference Include="..\Portal.Updater\Portal.Updater.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
    </ItemGroup>

    <PropertyGroup>
        <Authors>xXKoksMenXx</Authors>
        <Company>xXTeam</Company>
        <Product>Portal Host (Windows)</Product>
        <Copyright>Copyright © 2026</Copyright>
		<Version>1.5.4</Version>
		<AssemblyVersion>1.5.4.0</AssemblyVersion>
		<FileVersion>1.5.4.0</FileVersion>
		<InformationalVersion>1.5.4-Herta</InformationalVersion>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>

    <Target Name="SignOutput" AfterTargets="Build" Condition="'$(Configuration)' == 'Release' And '$(SkipSigning)' != 'true'">
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;F1A00AC831420B2AADEFD0BCCDFD99FDAF246D7B&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(TargetPath)&quot;" />
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;F1A00AC831420B2AADEFD0BCCDFD99FDAF246D7B&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(TargetDir)$(TargetName).exe&quot;" Condition="Exists('$(TargetDir)$(TargetName).exe')" />
    </Target>

    <Target Name="CopyCredentialProviderOutput" AfterTargets="Build;Publish">
        <ItemGroup>
            <CredentialProviderOutput Include="..\Portal.CredentialProvider\bin\$(Configuration)\$(TargetFramework)\**\*.*" />
        </ItemGroup>
        <Copy
            SourceFiles="@(CredentialProviderOutput)"
            DestinationFiles="@(CredentialProviderOutput->'$(TargetDir)CredentialProvider\%(RecursiveDir)%(Filename)%(Extension)')"
            SkipUnchangedFiles="true" />
        <Copy
            SourceFiles="@(CredentialProviderOutput)"
            DestinationFiles="@(CredentialProviderOutput->'$(PublishDir)CredentialProvider\%(RecursiveDir)%(Filename)%(Extension)')"
            SkipUnchangedFiles="true"
            Condition="'$(PublishDir)' != ''" />
    </Target>

    <Target Name="CopyUpdaterOutput" AfterTargets="Build;Publish">
        <ItemGroup>
            <UpdaterOutput Include="..\Portal.Updater\bin\$(Configuration)\$(TargetFramework)\**\*.*" />
        </ItemGroup>
        <Copy
            SourceFiles="@(UpdaterOutput)"
            DestinationFiles="@(UpdaterOutput->'$(TargetDir)Updater\%(RecursiveDir)%(Filename)%(Extension)')"
            SkipUnchangedFiles="true" />
        <Copy
            SourceFiles="@(UpdaterOutput)"
            DestinationFiles="@(UpdaterOutput->'$(PublishDir)Updater\%(RecursiveDir)%(Filename)%(Extension)')"
            SkipUnchangedFiles="true"
            Condition="'$(PublishDir)' != ''" />
    </Target>

    <Target Name="SignPublishOutput" AfterTargets="Publish" Condition="'$(Configuration)' == 'Release' And '$(SkipSigning)' != 'true'">
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;F1A00AC831420B2AADEFD0BCCDFD99FDAF246D7B&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(PublishDir)$(TargetName).dll&quot;" Condition="Exists('$(PublishDir)$(TargetName).dll')" />
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;F1A00AC831420B2AADEFD0BCCDFD99FDAF246D7B&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(PublishDir)$(TargetName).exe&quot;" Condition="Exists('$(PublishDir)$(TargetName).exe')" />
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;7492EFCAEAEFD328F405F05E0A6BCBF12402C7A8&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(PublishDir)Portal.Common.dll&quot;" Condition="Exists('$(PublishDir)Portal.Common.dll')" />
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;6B757026547640EBCDB08ACFD568F2A873D601F0&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(PublishDir)Portal.Updater.exe&quot;" Condition="Exists('$(PublishDir)Portal.Updater.exe')" />
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;6B757026547640EBCDB08ACFD568F2A873D601F0&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(PublishDir)Updater\Portal.Updater.exe&quot;" Condition="Exists('$(PublishDir)Updater\Portal.Updater.exe')" />
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;6B757026547640EBCDB08ACFD568F2A873D601F0&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(PublishDir)Updater\Portal.Updater.dll&quot;" Condition="Exists('$(PublishDir)Updater\Portal.Updater.dll')" />
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;7492EFCAEAEFD328F405F05E0A6BCBF12402C7A8&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(PublishDir)Updater\Portal.Common.dll&quot;" Condition="Exists('$(PublishDir)Updater\Portal.Common.dll')" />
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;110025BF33D9D8EEE632AD6C4F43618A24069B22&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(PublishDir)Portal.CredentialProvider.comhost.dll&quot;" Condition="Exists('$(PublishDir)Portal.CredentialProvider.comhost.dll')" />
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;110025BF33D9D8EEE632AD6C4F43618A24069B22&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(PublishDir)CredentialProvider\Portal.CredentialProvider.comhost.dll&quot;" Condition="Exists('$(PublishDir)CredentialProvider\Portal.CredentialProvider.comhost.dll')" />
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;110025BF33D9D8EEE632AD6C4F43618A24069B22&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(PublishDir)CredentialProvider\Portal.CredentialProvider.dll&quot;" Condition="Exists('$(PublishDir)CredentialProvider\Portal.CredentialProvider.dll')" />
        <Exec Command="call &quot;E:\Windows Kits\10\bin\10.0.26100.0\x86\signtool.exe&quot; sign /sha1 &quot;7492EFCAEAEFD328F405F05E0A6BCBF12402C7A8&quot; /tr http://timestamp.sectigo.com /td sha256 /fd sha256 &quot;$(PublishDir)CredentialProvider\Portal.Common.dll&quot;" Condition="Exists('$(PublishDir)CredentialProvider\Portal.Common.dll')" />
    </Target>

</Project>
