using System;
using System.Reflection;

namespace Portal.Common.Helpers;

/// <summary>
/// Centralized provider for solution versioning metadata.
/// Values are derived dynamically from assembly metadata generated by Directory.Build.props.
/// </summary>
public static class PortalVersionInfo
{
    private static readonly Lazy<(string version, string fullVersion, string codename)> _parsedVersion = new(() =>
    {
        var asm = typeof(PortalVersionInfo).Assembly;
        var infoVer = asm.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;

        if (!string.IsNullOrWhiteSpace(infoVer))
        {
            var plusIdx = infoVer.IndexOf('+');
            if (plusIdx >= 0)
            {
                infoVer = infoVer.Substring(0, plusIdx);
            }

            var dashIdx = infoVer.IndexOf('-');
            if (dashIdx >= 0)
            {
                var ver = infoVer.Substring(0, dashIdx);
                var code = infoVer.Substring(dashIdx + 1);
                return (ver, infoVer, code);
            }

            return (infoVer, infoVer, string.Empty);
        }

        var v = asm.GetName().Version;
        var fallbackVer = v != null ? $"{v.Major}.{v.Minor}.{v.Build}" : "1.7.0";
        return (fallbackVer, fallbackVer, string.Empty);
    });

    /// <summary>
    /// SemVer version string, e.g. "1.7.0".
    /// </summary>
    public static string Version => _parsedVersion.Value.version;

    /// <summary>
    /// User-facing display version, e.g. "v1.7.0".
    /// </summary>
    public static string DisplayVersion => "v" + _parsedVersion.Value.version;

    /// <summary>
    /// Full informational version including release codename, e.g. "1.7.0-Herta".
    /// </summary>
    public static string FullVersion => _parsedVersion.Value.fullVersion;

    /// <summary>
    /// Release codename, e.g. "Herta".
    /// </summary>
    public static string ReleaseCodename => _parsedVersion.Value.codename;
}
